version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: bookshop

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    command: ["npm", "run", "dev"]

  db:
    image: mysql:8.0
    restart: always
    platform: linux/arm64 
    environment:

      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: bookshop
      MYSQL_USER: devuser                 
      MYSQL_PASSWORD: devpassword   
      
    volumes:
      - my-db:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    # command: >
    #   bash -c "docker-entrypoint.sh mysqld & sleep 10 && 
    #   mysql -u root -prootpassword test < /docker-entrypoint-initdb.d/init.sql && wait"
    ports:
      - 3306:3306
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=rootpassword"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  # mysql_data: 
  my-db: