version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env 


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

  db:
    image: mysql:8.0
    platform: linux/amd64 
    container_name: bookshop-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password

   
    env_file:
      - ./backend/.env

    ports:
      - "3308:3306"
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 3
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data: 