version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydatabase
      DIALECT: mysql
      PORT: 8800

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

  db:
    image: mysql:5.7 
    platform: linux/amd64 
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: devuser  # Regular user (cannot be "root")
      MYSQL_PASSWORD: devpassword
      # MYSQL_USER: root
    ports:
      - "3308:3306"
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 3
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data: 